# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addrUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_allForm(object):
    def setupUi(self, allForm):
        allForm.setObjectName("allForm")
        allForm.setWindowModality(QtCore.Qt.ApplicationModal)
        allForm.resize(391, 491)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(allForm.sizePolicy().hasHeightForWidth())
        self.verticalLayoutWidget = QtWidgets.QWidget(allForm)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 391, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.allVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.allVerticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.allVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.allVerticalLayout.setObjectName("allVerticalLayout")
        self.allWidget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.allWidget.setObjectName("allWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.allWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 450, 381, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.button_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.button_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.button_horizontalLayout.setObjectName("button_horizontalLayout")
        self.frame_blank = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame_blank.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_blank.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_blank.setObjectName("frame_blank")
        self.button_horizontalLayout.addWidget(self.frame_blank)
        self.pushButton_ok = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.button_horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.button_horizontalLayout.addWidget(self.pushButton_cancel)
        self.button_horizontalLayout.setStretch(0, 6)
        self.button_horizontalLayout.setStretch(1, 2)
        self.button_horizontalLayout.setStretch(2, 2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.allWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 230, 391, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_info = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_info.setContentsMargins(2, 2, 2, 0)
        self.verticalLayout_info.setObjectName("verticalLayout_info")
        self.label_addr = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_addr.setObjectName("label_addr")
        self.verticalLayout_info.addWidget(self.label_addr)
        self.textEdit_addr = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.textEdit_addr.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_addr.setObjectName("textEdit_addr")
        self.verticalLayout_info.addWidget(self.textEdit_addr)
        self.label_info = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_info.setObjectName("label_info")
        self.verticalLayout_info.addWidget(self.label_info)
        self.textEdit_info = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.textEdit_info.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_info.setObjectName("textEdit_info")
        self.verticalLayout_info.addWidget(self.textEdit_info)
        self.verticalLayout_info.setStretch(0, 1)
        self.verticalLayout_info.setStretch(1, 3)
        self.verticalLayout_info.setStretch(2, 1)
        self.textEdit_addr.raise_()
        self.textEdit_info.raise_()
        self.label_info.raise_()
        self.label_addr.raise_()
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.allWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 391, 231))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_mainInfo = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_mainInfo.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_mainInfo.setObjectName("horizontalLayout_mainInfo")
        self.widget_mainInfo = QtWidgets.QWidget(self.horizontalLayoutWidget_2)
        self.widget_mainInfo.setObjectName("widget_mainInfo")
        self.photo_frame = QtWidgets.QFrame(self.widget_mainInfo)
        self.photo_frame.setGeometry(QtCore.QRect(250, 20, 120, 191))
        self.photo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.photo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.photo_frame.setObjectName("photo_frame")
        self.graphicsView = QtWidgets.QGraphicsView(self.photo_frame)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 120, 191))
        self.graphicsView.setObjectName("graphicsView")
        self.label_name = QtWidgets.QLabel(self.widget_mainInfo)
        self.label_name.setGeometry(QtCore.QRect(30, 20, 54, 12))
        self.label_name.setObjectName("label_name")
        self.lineEdit_name = QtWidgets.QLineEdit(self.widget_mainInfo)
        self.lineEdit_name.setGeometry(QtCore.QRect(30, 40, 113, 21))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_tel = QtWidgets.QLabel(self.widget_mainInfo)
        self.label_tel.setGeometry(QtCore.QRect(30, 70, 54, 12))
        self.label_tel.setObjectName("label_tel")
        self.lineEdit_tel = QtWidgets.QLineEdit(self.widget_mainInfo)
        self.lineEdit_tel.setGeometry(QtCore.QRect(30, 90, 201, 20))
        self.lineEdit_tel.setMaxLength(12)
        self.lineEdit_tel.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_tel.setObjectName("lineEdit_tel")
        self.label_group = QtWidgets.QLabel(self.widget_mainInfo)
        self.label_group.setGeometry(QtCore.QRect(150, 170, 54, 12))
        self.label_group.setObjectName("label_group")
        self.lineEdit_group = QtWidgets.QLineEdit(self.widget_mainInfo)
        self.lineEdit_group.setGeometry(QtCore.QRect(148, 190, 81, 21))
        self.lineEdit_group.setObjectName("lineEdit_group")
        self.label_birthday = QtWidgets.QLabel(self.widget_mainInfo)
        self.label_birthday.setGeometry(QtCore.QRect(30, 170, 54, 12))
        self.label_birthday.setObjectName("label_birthday")
        self.dateEdit_birthday = QtWidgets.QDateEdit(self.widget_mainInfo)
        self.dateEdit_birthday.setGeometry(QtCore.QRect(30, 190, 81, 21))
        self.dateEdit_birthday.setObjectName("dateEdit_birthday")
        self.label_email = QtWidgets.QLabel(self.widget_mainInfo)
        self.label_email.setGeometry(QtCore.QRect(30, 120, 54, 12))
        self.label_email.setObjectName("label_email")
        self.lineEdit_email = QtWidgets.QLineEdit(self.widget_mainInfo)
        self.lineEdit_email.setGeometry(QtCore.QRect(30, 140, 201, 20))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.checkBox_like = QtWidgets.QCheckBox(self.widget_mainInfo)
        self.checkBox_like.setGeometry(QtCore.QRect(170, 40, 71, 16))
        self.checkBox_like.setObjectName("checkBox_like")
        self.line = QtWidgets.QFrame(self.widget_mainInfo)
        self.line.setGeometry(QtCore.QRect(-10, 220, 401, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_mainInfo.addWidget(self.widget_mainInfo)
        self.allVerticalLayout.addWidget(self.allWidget)

        self.retranslateUi(allForm)
        self.pushButton_ok.clicked.connect(allForm.okButtonEvent)
        self.pushButton_cancel.clicked.connect(allForm.close)
        QtCore.QMetaObject.connectSlotsByName(allForm)

    def retranslateUi(self, allForm):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_ok.setText(_translate("allForm", "确定"))
        self.pushButton_cancel.setText(_translate("allForm", "取消"))
        self.label_addr.setText(_translate("allForm", "地址："))
        self.label_info.setText(_translate("allForm", "备注："))
        self.label_name.setText(_translate("allForm", "姓名"))
        self.label_tel.setText(_translate("allForm", "电话"))
        self.label_group.setText(_translate("allForm", "分组"))
        self.label_birthday.setText(_translate("allForm", "生日"))
        self.label_email.setText(_translate("allForm", "邮箱"))
        self.checkBox_like.setText(_translate("allForm", "收藏"))

